### ISSUE TITLE
Spelling error in comment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [alexwlchan/apachelog#4]
```
There is a spelling error in the comment describing the built in formats.
There is a missing 'e' on 'apachelog'.

patch included for fix.
```

Original issue reported on code.google.com by `cart...@gmail.com` on 25 Jul 2007 at 3:40

Attachments:
* [spelling.patch](https://storage.googleapis.com/google-code-attachments/apachelog/issue-4/comment-0/spelling.patch)

**Comment by alexwlchan** [comment]
Resolved by 38eadbc
